# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow_.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1698, 860)
        MainWindow.setStyleSheet("background-color: rgb(7, 59, 75);\n"
"border-color: rgb(255, 255, 255);\n"
"color: white;\n"
"font: bold 12px ;\n"
"\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.PreferAntialias)
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet("QTabWidget {\n"
"    /* Set the background color of the tab widget */\n"
"    background-color: #f0f0f0;\n"
"}\n"
"\n"
"QTabBar::tab {\n"
"    /* Define styles for each tab */\n"
"    background-color: #e0e0e0; /* Background color */\n"
"    color: #333333; /* Text color */\n"
"    padding: 8px 16px; /* Padding */\n"
"    margin-top: 2px; /* Top margin */\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    /* Define styles for the selected tab */\n"
"    background-color: #ffffff; /* Background color */\n"
"    color: #000000; /* Text color */\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    /* Define styles for when hovering over a tab */\n"
"    background-color: #d0d0d0; /* Background color */\n"
"}\n"
"\n"
"QTabWidget::pane {\n"
"    /* Define styles for the area holding the tab contents */\n"
"    border: 1px solid #cccccc; /* Border color */\n"
"    background-color: #ffffff; /* Background color */\n"
"    margin-top: -1px; /* Negative margin to overlap border */\n"
"}\n"
"")
        self.tabWidget.setMovable(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout()
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setObjectName("label")
        self.verticalLayout_4.addWidget(self.label)
        self.grph_input = PlotWidget(self.tab_3)
        self.grph_input.setObjectName("grph_input")
        self.verticalLayout_4.addWidget(self.grph_input)
        self.verticalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.start_btn = QtWidgets.QPushButton(self.tab_3)
        self.start_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.start_btn.setObjectName("start_btn")
        self.horizontalLayout_4.addWidget(self.start_btn)
        self.label_7 = QtWidgets.QLabel(self.tab_3)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.slider_process_speed = QtWidgets.QSlider(self.tab_3)
        self.slider_process_speed.setStyleSheet("QSlider {\n"
"    background: rgb(7, 59, 75);\n"
"}\n"
"\n"
"QSlider::handle {\n"
"   background:rgb(7, 59, 75);\n"
"    border: 2px solid white;\n"
"    width: 8px;\n"
"    height: 2px;\n"
"    border-radius: 6px;\n"
"\n"
"}")
        self.slider_process_speed.setMaximum(100)
        self.slider_process_speed.setOrientation(QtCore.Qt.Horizontal)
        self.slider_process_speed.setObjectName("slider_process_speed")
        self.horizontalLayout_4.addWidget(self.slider_process_speed)
        self.verticalLayout_10.addLayout(self.horizontalLayout_4)
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_5.addWidget(self.label_2)
        self.grph_filter = PlotWidget(self.tab_3)
        self.grph_filter.setObjectName("grph_filter")
        self.verticalLayout_5.addWidget(self.grph_filter)
        spacerItem = QtWidgets.QSpacerItem(1501, 0, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_5.addItem(spacerItem)
        self.verticalLayout_10.addLayout(self.verticalLayout_5)
        self.gridLayout_3.addLayout(self.verticalLayout_10, 1, 0, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.import_button = QtWidgets.QPushButton(self.tab_3)
        self.import_button.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.import_button.setObjectName("import_button")
        self.verticalLayout_3.addWidget(self.import_button)
        self.pad_check = QtWidgets.QCheckBox(self.tab_3)
        self.pad_check.setObjectName("pad_check")
        self.verticalLayout_3.addWidget(self.pad_check)
        self.clears_btn = QtWidgets.QPushButton(self.tab_3)
        self.clears_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.clears_btn.setObjectName("clears_btn")
        self.verticalLayout_3.addWidget(self.clears_btn)
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.padding_area = PlotWidget(self.tab_3)
        self.padding_area.setObjectName("padding_area")
        self.verticalLayout_3.addWidget(self.padding_area)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 1, 2, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_6 = QtWidgets.QLabel(self.tab_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_8.addWidget(self.label_6)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_8.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.checkBox_conj = QtWidgets.QCheckBox(self.tab_3)
        self.checkBox_conj.setObjectName("checkBox_conj")
        self.verticalLayout_9.addWidget(self.checkBox_conj)
        self.combx_zero_pole = QtWidgets.QComboBox(self.tab_3)
        self.combx_zero_pole.setStyleSheet("QComboBox {\n"
"    border: 2px solid white; \n"
"    border-radius: 5px; \n"
"    padding: 1px 18px 1px 3px; \n"
"    background-color: rgb(7, 59, 75); \n"
"  \n"
"}")
        self.combx_zero_pole.setObjectName("combx_zero_pole")
        self.combx_zero_pole.addItem("")
        self.combx_zero_pole.addItem("")
        self.verticalLayout_9.addWidget(self.combx_zero_pole)
        self.btn_clr_zero = QtWidgets.QPushButton(self.tab_3)
        self.btn_clr_zero.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.btn_clr_zero.setObjectName("btn_clr_zero")
        self.verticalLayout_9.addWidget(self.btn_clr_zero)
        self.btn_clr_pole = QtWidgets.QPushButton(self.tab_3)
        self.btn_clr_pole.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.btn_clr_pole.setObjectName("btn_clr_pole")
        self.verticalLayout_9.addWidget(self.btn_clr_pole)
        self.btn_clr_all = QtWidgets.QPushButton(self.tab_3)
        self.btn_clr_all.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.btn_clr_all.setObjectName("btn_clr_all")
        self.verticalLayout_9.addWidget(self.btn_clr_all)
        self.horizontalLayout.addLayout(self.verticalLayout_9)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_7.addWidget(self.label_4)
        self.grph_mag_response = PlotWidget(self.tab_3)
        self.grph_mag_response.setObjectName("grph_mag_response")
        self.verticalLayout_7.addWidget(self.grph_mag_response)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_5 = QtWidgets.QLabel(self.tab_3)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_2.addWidget(self.label_5)
        self.grph_phase_response = PlotWidget(self.tab_3)
        self.grph_phase_response.setObjectName("grph_phase_response")
        self.verticalLayout_2.addWidget(self.grph_phase_response)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 0, 1, 3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 550, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem1, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem2, 3, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.tab_4)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout.addWidget(self.doubleSpinBox)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.groupBox)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout.addWidget(self.doubleSpinBox_2)
        self.add_filter_btn_2 = QtWidgets.QPushButton(self.groupBox)
        self.add_filter_btn_2.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.add_filter_btn_2.setObjectName("add_filter_btn_2")
        self.verticalLayout.addWidget(self.add_filter_btn_2)
        self.gridLayout_2.addWidget(self.groupBox, 2, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem3, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 525, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout_2.addItem(spacerItem4, 0, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.tab_4)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem5 = QtWidgets.QSpacerItem(0, 352, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.gridLayout.addItem(spacerItem5, 0, 2, 1, 1)
        self.apply_check = QtWidgets.QCheckBox(self.widget)
        self.apply_check.setObjectName("apply_check")
        self.gridLayout.addWidget(self.apply_check, 6, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 2, 0, 1, 1)
        self.tableWidget = QtWidgets.QTableWidget(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.gridLayout.addWidget(self.tableWidget, 0, 0, 2, 2)
        self.filters_combo = QtWidgets.QComboBox(self.widget)
        self.filters_combo.setStyleSheet("QComboBox {\n"
"    border: 2px solid white; \n"
"    border-radius: 5px; \n"
"    padding: 1px 18px 1px 3px; \n"
"    background-color: rgb(7, 59, 75); \n"
"  \n"
"}")
        self.filters_combo.setObjectName("filters_combo")
        self.filters_combo.addItem("")
        self.filters_combo.addItem("")
        self.filters_combo.addItem("")
        self.filters_combo.addItem("")
        self.gridLayout.addWidget(self.filters_combo, 3, 0, 1, 2)
        self.remove_filter_btn = QtWidgets.QPushButton(self.widget)
        self.remove_filter_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.remove_filter_btn.setObjectName("remove_filter_btn")
        self.gridLayout.addWidget(self.remove_filter_btn, 4, 0, 1, 2)
        self.add_filter_btn = QtWidgets.QPushButton(self.widget)
        self.add_filter_btn.setStyleSheet("QPushButton {\n"
"    background-color: rgb(7, 59, 75);\n"
"    border-radius: 5px;\n"
"    border: 2px solid white;\n"
"    padding: 4px;\n"
"}")
        self.add_filter_btn.setObjectName("add_filter_btn")
        self.gridLayout.addWidget(self.add_filter_btn, 5, 0, 1, 2)
        self.gridLayout_2.addWidget(self.widget, 0, 0, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_9 = QtWidgets.QLabel(self.tab_4)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_6.addWidget(self.label_9)
        self.allpass_grph = PlotWidget(self.tab_4)
        self.allpass_grph.setObjectName("allpass_grph")
        self.verticalLayout_6.addWidget(self.allpass_grph)
        self.label_10 = QtWidgets.QLabel(self.tab_4)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_6.addWidget(self.label_10)
        self.allpass_grph_2 = PlotWidget(self.tab_4)
        self.allpass_grph_2.setObjectName("allpass_grph_2")
        self.verticalLayout_6.addWidget(self.allpass_grph_2)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 2, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_6.addItem(spacerItem6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.gridLayout_5.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1698, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Orignal signal"))
        self.start_btn.setText(_translate("MainWindow", "Start"))
        self.label_7.setText(_translate("MainWindow", "Point/sec"))
        self.label_2.setText(_translate("MainWindow", "Filterd signal"))
        self.import_button.setText(_translate("MainWindow", "Import Signal"))
        self.pad_check.setText(_translate("MainWindow", "Mouse pad mode"))
        self.clears_btn.setText(_translate("MainWindow", "Clear"))
        self.label_3.setText(_translate("MainWindow", "Padding area"))
        self.label_6.setText(_translate("MainWindow", "z-plane"))
        self.checkBox_conj.setText(_translate("MainWindow", "Add conjigate"))
        self.combx_zero_pole.setItemText(0, _translate("MainWindow", "add zero"))
        self.combx_zero_pole.setItemText(1, _translate("MainWindow", "add pole"))
        self.btn_clr_zero.setText(_translate("MainWindow", "clear all zeros"))
        self.btn_clr_pole.setText(_translate("MainWindow", "clear all poles"))
        self.btn_clr_all.setText(_translate("MainWindow", "clear all "))
        self.label_4.setText(_translate("MainWindow", "Magnitude response"))
        self.label_5.setText(_translate("MainWindow", "Phase response"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("MainWindow", "filter design"))
        self.groupBox.setTitle(_translate("MainWindow", "custom filter"))
        self.add_filter_btn_2.setText(_translate("MainWindow", "Add"))
        self.apply_check.setText(_translate("MainWindow", "Apply"))
        self.label_8.setText(_translate("MainWindow", "Filter Coefficient"))
        self.filters_combo.setItemText(0, _translate("MainWindow", "1"))
        self.filters_combo.setItemText(1, _translate("MainWindow", "2"))
        self.filters_combo.setItemText(2, _translate("MainWindow", "-1"))
        self.filters_combo.setItemText(3, _translate("MainWindow", ".5"))
        self.remove_filter_btn.setText(_translate("MainWindow", "Remove"))
        self.add_filter_btn.setText(_translate("MainWindow", "Add"))
        self.label_9.setText(_translate("MainWindow", "filter"))
        self.label_10.setText(_translate("MainWindow", "final phase gain"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("MainWindow", "all pass filter"))
from pyqtgraph import PlotWidget
