# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(920, 654)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.grph_zero_plot = PlotWidget(self.centralwidget)
        self.grph_zero_plot.setObjectName("grph_zero_plot")
        self.horizontalLayout_2.addWidget(self.grph_zero_plot)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_clr_all = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr_all.setObjectName("btn_clr_all")
        self.verticalLayout.addWidget(self.btn_clr_all)
        self.btn_clr_zero = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr_zero.setObjectName("btn_clr_zero")
        self.verticalLayout.addWidget(self.btn_clr_zero)
        self.btn_clr_pole = QtWidgets.QPushButton(self.centralwidget)
        self.btn_clr_pole.setObjectName("btn_clr_pole")
        self.verticalLayout.addWidget(self.btn_clr_pole)
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.grph_mag_response = PlotWidget(self.centralwidget)
        self.grph_mag_response.setObjectName("grph_mag_response")
        self.horizontalLayout.addWidget(self.grph_mag_response)
        self.grph_phase_response = PlotWidget(self.centralwidget)
        self.grph_phase_response.setObjectName("grph_phase_response")
        self.horizontalLayout.addWidget(self.grph_phase_response)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 920, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_clr_all.setText(_translate("MainWindow", "clear all zeros & poles"))
        self.btn_clr_zero.setText(_translate("MainWindow", "clear all zeros"))
        self.btn_clr_pole.setText(_translate("MainWindow", "clear all poles"))
        self.checkBox.setText(_translate("MainWindow", "add conjigate"))
from pyqtgraph import PlotWidget
